package com.github.bjones1.intellij.codechat.gen_java;

/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class CodeChat_ServicesConstants {

  public static final short THRIFT_PORT = (short)27376;

}
